# Generated by Django 6.0 on 2025-12-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='123456', help_text='The access code required for admin login', max_length=10)),
            ],
            options={
                'verbose_name': 'Access Code',
                'verbose_name_plural': 'Access Codes',
            },
        ),
    ]
