# Generated by Django 6.0 on 2026-01-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_debtor_debtoritem_product_sale_saleitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bath', 'Bath, Hygiene & Laundry Soaps'), ('foods', 'Whole Foods'), ('beverages', 'Beverages'), ('wholesale_beverages', 'Wholesale Beverages'), ('school', 'School Supplies'), ('liquor', 'Hard Liquors'), ('snacks', 'Snacks')], max_length=30),
        ),
    ]
