# Generated by Django 6.0.1 on 2026-01-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sale_profit_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('low_stock_limit', models.IntegerField(default=5)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('theme', models.CharField(default='light', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
