# Generated by Django 6.0.1 on 2026-01-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_storesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='sound_enabled',
        ),
    ]
